Table posts {
    id integer [pk, increment] // A primary key column is usually included but not explicitly defined in your migration
    title varchar(255)
    body text
    created datetime
    modified datetime
}